### ISSUE TITLE
The doc is missing some installation instruction

### ISSUE THREAD

**Issue by Remi-Gau** [CyclotronResearchCentre/bidsme#1]
I don't believe bidsme is installable with `pip install`, right?

So there should be some minimum installation instruction because otherwise the whole thing could be a non starter.

**Comment by MartinGrignard** [comment]
Hi,
If that can help you, here is a subset of the commands I use in my dockerfile:
```shell
cd /opt
wget -O bidsme.tar.gz https://github.com/CyclotronResearchCentre/bidsme/archive/1.3.5r1.tar.gz
tar -xvf bidsme.tar.gz
mv bidsme-* bidsme
cd bidsme
python3 -m pip install --no-cache-dir --no-input --upgrade -r requirements.txt
echo 'python3 /opt/bidsme/bidsme/bidsme.py $*' > /usr/bin/bidsme
chmod a+x /usr/bin/bidsme
```
After that, you can use BIDSme with `bidsme <sub-command> ...` :slightly_smiling_face:

**Comment by MartinGrignard** [comment]
One year later, it is still not possible to install BIDSme using a simple `pip install` or `conda install`. Is there a reason preventing that?

**Comment by nbeliy** [comment]
Since few 1.4.0 bidsme is installable via pip (but still using direct git path).
Main doc, including installation was moved to separate repository: https://gitlab.uliege.be/CyclotronResearchCentre/Public/bidstools/bidsme/bidsme_tutorial
