### ISSUE TITLE
JOSS Review — Quality of writing

### ISSUE THREAD

**Issue by TheChymera** [CyclotronResearchCentre/bidsme#12]
As part of the JOSS review: https://github.com/openjournals/joss-reviews/issues/5575

## Suggestions:
1. Please consider splitting the source code over more lines, ideally one line per sentence to make things easier to reference.
2. Please consider using the term “directories” instead of “folders”. Directories are file system entities, whereas folders are graphical interface features.

## Minor issues:
1. Python is a proper noun and should be capitalized, at least in formal writing; python is a type of snake.

## Major issues:
1. “imposing only the core of BIDS -- the folder structure, the file naming style and the global metadata”. The term “global metadata” is unclear so you would need to introduce and explain it. To my knowledge, “global metadata” is not a core concept in BIDS. I would guess you mean simply `dataset_description.json` — but then again, you do not show this file, but you show e.g. `participants.tsv`, a different metadata file, in the figure.

**Comment by nbeliy** [comment]
Hi @TheChymera 

Thanks for the comments.

> “imposing only the core of BIDS -- the folder structure, the file naming style and the global metadata”

Under global I meant here the column `participant_id` in `participants.tsv` and `*_scans.tsv`. Will it be better to remove of mention of `global metadata` completely?

> Python is a proper noun and should be capitalized

Good point

>  Please consider using the term “directories” instead of “folders”.

Will do

> Please consider splitting the source code over more lines,

Can you provide more details/examples? I used flake8 which warns about long lines and usage of multiple directives on same line -- so normally the source code already splitted over multiple lines.

**Comment by nbeliy** [comment]
Hi @TheChymera,

I've added integration test, and fixed your smaller remarks. For the `global metadata` I still searching how to reformulate.

**Comment by TheChymera** [comment]
> Will it be better to remove of mention of global metadata completely?

Not necessarily, you can add a sentence saying “we define *global metadata* as ...”, then you write what it is, and “global metadata” will be a specific term introduced by your article. The problem is it sounds like it's a BIDS term, which it is not. I do think it would be better to not introduce a new term though, and just call it “select metadata”. Or if you only mention it once, just say what metadata you mean.

---


> Please consider splitting the source code over more lines

> Can you provide more details/examples?

I mean the “code” in the document source

I.e. instead of:

```
In this article we tackle this problem. This is an important problem because of the following implications. Our solution is amazing as demonstrated by the following results.
```

The following makes review easier. This is because I can reference line numbers instead of copying text that's otherwise hard to navigate to — also, it has the advantage over fixed-length line breaks, that you don't need to re-write the paragraph after you change the length of the first line :3

```
In this article we tackle this problem.
This is an important problem because of the following implications.
Our solution is amazing as demonstrated by the following results.
```

But it was just a suggestion, so don't worry. Maybe think of it for the next article, we can move on with the actual issues here. Please link commits with the fixes.

**Comment by nbeliy** [comment]
Hi @TheChymera ,

I rephrased the `core metadata` into :
> some minimal metadata (those included in `participants.tsv and` `*_scans.tsv` tabular files)

I believe that that fixes this issue (please correct if I missed something)

**Comment by TheChymera** [comment]
Yes, that addresses the issue.
