### ISSUE TITLE
model: fmap:TB1AFI raises an Error when specifying 'RepetitionTime'

### ISSUE THREAD

**Issue by nkuegler** [CyclotronResearchCentre/bidsme#17]
I believe that I caught a bug:

I specified the RepetitionTime parameter in TB1AFI and during the bidsmap creation (checked: false) it kept raising an error that the "extra field RepetitionTime" does not comply with any rules. However, the field is mandatory for TB1AFI maps.

**Comment by nbeliy** [comment]
Hi @nkuegler , can you give the version of bids schema (must be reported at initialisation of bidsme)?
Also can you give me the log reports in which the error occures? Most importently the lines similar to:
```
bidsme.schema.BIDSschema(442) - INFO Matched fmap/fieldmaps rule
```

**Comment by nbeliy** [comment]
Are you sure that it's mandatory? From the rules in schema, I see `RepetitionTime` defined only for mrs and func.

An update, indeed the appendix states that RT is mandatory, but I can't find a corresponding rule in schema. I would report this to the BIDS team.

Bidsme now relies purely on schema, so there's no other solution but fix all other issues with TB1AFI (if any), and set checked to true. This will switch off all the validations.

**Comment by nkuegler** [comment]
Hi Nikita, 

this is the version: 
```
main(82) - INFO -------------- START bidsme ----------------
main(83) - INFO Thu Dec 19 13:07:49 2024
main(84) - INFO version: 1.8.1
bidsme.schema.BIDSschema(670) - INFO Loaded BIDS schema version 1.10.0
```

and here the error: 
```
bidsme.mapper(63) - INFO Processing: sub 'sub-002', ses 'ses-01', 031-kp_afib1_v1g/0 (2 files)
bidsme.mapper(153) - INFO Validating file fmap/sub-002_ses-01_acq-tr1_echo-1_TB1AFI
bidsme.schema.BIDSschema(442) - INFO Matched fmap/RFFieldMaps rule
bidsme.schema.BIDSschema(648) - ERROR Extra field 'RepetitionTime' do not match any rules
bidsme.schema.BIDSschema(655) - INFO The time in seconds between the beginning of an acquisition of one volume
and the beginning of acquisition of the volume following it (TR).
When used in the context of functional acquisitions this parameter best
corresponds to
[DICOM Tag 0020, 0110](http://dicomlookup.com/dicomtags/(0020,0110)):
the "time delta between images in a
dynamic of functional set of images" but may also be found in
[DICOM Tag 0018, 0080](http://dicomlookup.com/dicomtags/(0018,0080)):
"the period of time in msec between the beginning
of a pulse sequence and the beginning of the succeeding
(essentially identical) pulse sequence".
This definition includes time between scans (when no data has been acquired)
in case of sparse acquisition schemes.
This value MUST be consistent with the 'pixdim[4]' field (after accounting
for units stored in 'xyzt_units' field) in the NIfTI header.
This field is mutually exclusive with VolumeTiming.
```


I did not check the schema but the documentation of the quantitative MRI lists `RepetitionTime` as required metadata for TB1AFI (https://bids-specification.readthedocs.io/en/stable/appendices/qmri.html#field-maps)

I see. This solution works for me. Thanks for checking!

**Comment by nbeliy** [comment]
FYI: Apparently the correct metadata is `RepetitionTimeExcitation`: https://github.com/bids-standard/bids-specification/pull/2020

I think that wthe documentation will be corrected soon.

I will close this issue, as in any case, the real issue is with BIDS documentation and not with `bidsme`
