### ISSUE TITLE
`bidsme map` command should not remove comments from `bidsmap.yaml`

### ISSUE THREAD

**Issue by MartinGrignard** [CyclotronResearchCentre/bidsme#2]
Building the `bidsmap.yaml` file is a tedious and repetitive task. The `template` and `checked` flags are great to have a broad view of what remains to do. Considering the number of fields to fill in, I'd like to be able to add comments to the bidsmap so that I can remember why I made some choices.

For now, adding comments to the bidsmap does not prevent the `bidmse map` command from running but the comments are removed by the program.

**Comment by nbeliy** [comment]
Unfortunally `ruamel` do not allow reading and thus conserving comments.
I could imagine an additional field `notes` or `comments` but I'm afraid it will render already complex yamel structure worse, to think
