### ISSUE TITLE
`bidsme map` raises no error but `bidsme bidsify` does

### ISSUE THREAD

**Issue by MartinGrignard** [CyclotronResearchCentre/bidsme#3]
While building the bidsmap for a dataset, I ended up with `bidsme map` raising no error at all but once I run `bidsme bidsify`, I get `FileExistsError`.

This means that `bidsme map` does not capture some existing conflicts. Maybe this should be fixed to make the process of creating the bidsmap less frustrating. It looks to me like one of the sanity checks performed during `bidsme map` should handle this.

**Comment by nbeliy** [comment]
@MartinGrignard 
At current state `map` checks for duplicated names in two cases:
 - Inside a series, if there any file with same name as first file in series
 - Outside a series if there a first file of series duplicates any first file of already processed series

Do a full check of all bidsified names could be coustly both in memory (some fmri can have thousends of individual files),
and i time.

If you provide a concrete example what files was in conflict, I could imagine a quick test for that particular case.
