### ISSUE TITLE
JOSS review - examples

### ISSUE THREAD

**Issue by PeerHerholz** [CyclotronResearchCentre/bidsme#6]
Ahoi hoi @nbeliy & co-authors,

this is in reference to the review I'm currently conducting for `JOSS` [here](https://github.com/openjournals/joss-reviews/issues/5575) .

First of all, thank you very much for your dedicated work on this tool and your respective submission to `JOSS`.
Based on the [review process and included checkboxes](https://github.com/openjournals/joss-reviews/issues/5575#issuecomment-1627300948), I would like to suggest a few things.

Concerning the examples, I would like to suggest streamlining the existing example and maybe splitting it across fewer files to make it easier for interested users to follow and add examples for the other modalities you support. Both points target utilization and adaptation by the community.

I'm very sorry if I missed something obvious, misunderstood something or assumed something wrong. Please let me know if that is the case, as well as if you have any questions. Thanks again for creating this important software tool.

Cheers, Peer

**Comment by nbeliy** [comment]
The example is the tutorial. I have plans to make more direct example, but it may take time...

**Comment by PeerHerholz** [comment]
Hi @nbeliy,

thanks for the update. Just confirming with @emdupre if this works re the `JOSS` requirements?

**Comment by emdupre** [comment]
Hi @nbeliy and @PeerHerholz, and thanks for starting this conversation !

For the JOSS review process, we require:

> Example usage
> The authors should include examples of how to use the software (ideally to solve real-world analysis problems).

as [noted here](https://joss.readthedocs.io/en/latest/review_criteria.html#example-usage). The tutorial content appears to meet this requirement, though I would like to hear @PeerHerholz and @TheChymera 's opinions.

I notice, though, that the tutorial is only included in another repository (i.e., `bidsme_tutorial`). Since `bidsme` rather than `bidsme_tutorial` has been submitted for review, I would expect that the tutorial would be included in this code base. Could you please correct this @nbeliy, such that only code in the current repository is under review ?

**Comment by ChristophePhillips** [comment]
Hi @emdupre and @PeerHerholz,

Thank you for your constructive feedback!

FYI @nbeliy is currently enjoying a well deserved holiday break, so we'll come back to you in a couple of weeks only. 😃

**Comment by TheChymera** [comment]
@emdupre I believe examples have been adequately provided, in the tutorials as well as the test suite the author has now set up. As for tutorials being included in the actual repository or elsewhere, I guess ultimately it's up to editorial discretion — I'd just mention that there is such a thing as bundling too many things together, and perhaps users of the package don't want to download the tutorial source alongside with the code.

**Comment by emdupre** [comment]
Thanks for confirming, @TheChymera ! 

Yes, I don't mean to suggest that everything associated with BIDSme should be in one place ; we do expect, though that there is sufficient documentation inside the repository under review ! If there is other content already in the repository that meets that the JOSS example usage criteria (noted above) this would also be fine. It seems that @PeerHerholz was not originally able to find it, though this might have changed as the test suite was added. I'll let you (@TheChymera and @PeerHerholz) confirm.

**Comment by PeerHerholz** [comment]
Hi folks,

thanks for following up on this. My comment was more related to the structure and outline of the examples.
I think with the recent changes and current state [here](https://github.com/CyclotronResearchCentre/bidsme/tree/joss_paper) potential users can find and navigate examples/tutorials sufficiently. Thus, if everyone is ok with the current state, I'm too.

**Comment by nbeliy** [comment]
Closed as published
