### ISSUE TITLE
JOSS review - community guidelines

### ISSUE THREAD

**Issue by PeerHerholz** [CyclotronResearchCentre/bidsme#8]
Ahoi hoi @nbeliy & co-authors,

this is in reference to the review I'm currently conducting for `JOSS` [here](https://github.com/openjournals/joss-reviews/issues/5575) .

First of all, thank you very much for your dedicated work on this tool and your respective submission to `JOSS`.
Based on the [review process and included checkboxes](https://github.com/openjournals/joss-reviews/issues/5575#issuecomment-1627300948), I would like to suggest a few things.

Could you maybe add information concerning 

`1) Contribute to the software 2) Report issues or problems with the software 3) Seek support`

for interested users?

I'm very sorry if I missed something obvious, misunderstood something or assumed something wrong. Please let me know if that is the case, as well as if you have any questions. Thanks again for creating this important software tool.

Cheers, Peer

**Comment by nbeliy** [comment]
Hi @PeerHerholz,

Can you tell if the current contribution guide is satisfactory for you? And if so, can you close the issue?

**Comment by PeerHerholz** [comment]
Hi @nbeliy,

I think so, thanks for your work on this! I think the only thing left would be to mention/link it in the `README.md`.

**Comment by nbeliy** [comment]
Hi @PeerHerholz ,
I updated readme, can you check if references are clearer now?

**Comment by PeerHerholz** [comment]
Hi @nbeliy,

yes, thanks for implementing the changes!
